# Generated by Django 5.2.11 on 2026-02-23 13:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('patient_id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Identifier of the patient this record belongs to.')),
                ('encrypted_payload', models.TextField(help_text='Base64-encoded AES-256-CBC ciphertext (IV prepended).')),
                ('encrypted_aes_key', models.TextField(help_text='Base64-encoded AES session key wrapped with ECC.')),
                ('ephemeral_public_key', models.TextField(help_text='Base64-encoded ephemeral ECC public key used during encryption.')),
                ('integrity_hash', models.CharField(help_text='SHA-256 hex digest of the ciphertext for tamper detection.', max_length=64)),
            ],
            options={
                'verbose_name': 'medical record',
                'verbose_name_plural': 'medical records',
                'db_table': 'medical_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
