# Generated by Django 5.2.11 on 2026-02-23 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='created_by',
            field=models.ForeignKey(help_text='The user who submitted this record.', on_delete=django.db.models.deletion.PROTECT, related_name='medical_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['patient_id'], name='idx_patient_id'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['created_at'], name='idx_created_at'),
        ),
    ]
