# Generated by Django 5.2.11 on 2026-08-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='medicalrecord',
            name='idx_patient_id',
        ),
        migrations.RemoveIndex(
            model_name='medicalrecord',
            name='idx_created_at',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='risk_level',
            field=models.CharField(blank=True, help_text='Predicted patient risk level.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='risk_score',
            field=models.FloatField(blank=True, help_text='Prediction confidence score.', null=True),
        ),
        migrations.AlterModelTable(
            name='medicalrecord',
            table=None,
        ),
    ]
