# Generated by Django 5.2.11 on 2026-08-05 16:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0003_alter_medicalrecord_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'ordering': ['-created_at'], 'verbose_name': 'medical record', 'verbose_name_plural': 'medical records'},
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='prediction_time',
            field=models.DateTimeField(blank=True, help_text='Time when AI prediction was generated.', null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='recommendation',
            field=models.TextField(blank=True, help_text='AI-generated medical recommendation.', null=True),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['patient_id'], name='idx_patient_id'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['created_at'], name='idx_created_at'),
        ),
        migrations.AlterModelTable(
            name='medicalrecord',
            table='medical_records',
        ),
    ]
