# Generated by Django 5.2.11 on 2026-08-05 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0004_alter_medicalrecord_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'ordering': ['-created_at'], 'verbose_name': 'Medical Record', 'verbose_name_plural': 'Medical Records'},
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='ai_model',
            field=models.CharField(default='Random Forest', help_text='Machine Learning model used.', max_length=50),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='model_version',
            field=models.CharField(default='v1.0', help_text='Version of AI model.', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='created_by',
            field=models.ForeignKey(help_text='User who uploaded the record.', on_delete=django.db.models.deletion.PROTECT, related_name='medical_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='encrypted_aes_key',
            field=models.TextField(help_text='ECC wrapped AES session key.'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='encrypted_payload',
            field=models.TextField(help_text='Base64 encoded AES encrypted medical payload.'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='ephemeral_public_key',
            field=models.TextField(help_text='Ephemeral ECC public key.'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='integrity_hash',
            field=models.CharField(help_text='SHA-256 integrity hash.', max_length=64),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='recommendation',
            field=models.TextField(blank=True, help_text='AI generated recommendation.', null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='risk_level',
            field=models.CharField(blank=True, help_text='Predicted Risk Level (Low, Medium, High).', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='risk_score',
            field=models.FloatField(blank=True, help_text='Prediction confidence percentage.', null=True),
        ),
    ]
