# Generated by Django 5.2.11 on 2026-08-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0005_alter_medicalrecord_options_medicalrecord_ai_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='ai_model_accuracy',
            field=models.FloatField(blank=True, help_text='Model evaluation accuracy.', null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='ai_model_name',
            field=models.CharField(blank=True, help_text='Machine learning model used.', max_length=100, null=True),
        ),
    ]
