# Generated by Django 4.2.30 on 2026-08-15 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0006_medicalrecord_ai_model_accuracy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='ai_model',
        ),
    ]
