#!/usr/bin/env python
"""
IoT Device Simulator — Secure Fog Healthcare.

Simulates an IoT medical device that:
1. Generates sample patient vital signs.
2. Encrypts the data with AES-256-CBC.
3. Wraps the AES key with the Fog node's ECC public key (SECP256R1).
4. Computes a SHA-256 integrity hash.
5. Sends the encrypted payload to the Fog REST API.

Usage:
    # First generate keys (if not already done):
    python scripts/generate_keys.py

    # Then start the Django dev server in another terminal:
    python manage.py runserver

    # Run the simulator:
    python scripts/iot_simulator.py

Options (environment variables):
    FOG_API_URL      – Fog API base URL  (default: http://localhost:8000/api/v1)
    FOG_USERNAME     – Login username     (default: doctor1)
    FOG_PASSWORD     – Login password     (default: doctor1pass)
    ITERATIONS       – Number of records  (default: 3)
"""

from __future__ import annotations

import json
import os
import random
import sys
import uuid
from datetime import datetime, timezone
from pathlib import Path

import requests

# ── Bootstrap ────────────────────────────────────────────────
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

# Configure Django before importing any app modules
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings.dev")

import django  # noqa: E402
django.setup()  # noqa: E402

from apps.encryption.services import HybridEncryptionService  # noqa: E402

# ── Configuration ────────────────────────────────────────────
FOG_API_URL: str = os.getenv("FOG_API_URL", "http://localhost:8000/api/v1")
FOG_USERNAME: str = os.getenv("FOG_USERNAME", "doctor1")
FOG_PASSWORD: str = os.getenv("FOG_PASSWORD", "doctor1pass")
ITERATIONS: int = int(os.getenv("ITERATIONS", "3"))
FOG_PUBLIC_KEY_PATH: Path = PROJECT_ROOT / "keys" / "fog_public_key.pem"


# ── Sample Data Generator ───────────────────────────────────

def generate_vital_signs() -> dict:
    """Generate realistic-looking patient vital signs.

    Returns:
        Dictionary with simulated medical data.
    """
    return {
        "patient_id": str(uuid.uuid4()),
        "device_id": f"IOT-{random.randint(1000, 9999)}",
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "vitals": {
            "heart_rate": random.randint(60, 100),
            "blood_pressure": {
                "systolic": random.randint(110, 140),
                "diastolic": random.randint(70, 90),
            },
            "temperature_celsius": round(random.uniform(36.1, 37.8), 1),
            "oxygen_saturation": random.randint(95, 100),
            "respiratory_rate": random.randint(12, 20),
        },
        "notes": "Auto-generated by IoT simulator.",
    }


# ── Main ─────────────────────────────────────────────────────

def main() -> None:
    """Run the IoT simulation loop."""
    print("=" * 60)
    print("  IoT Device Simulator — Secure Fog Healthcare")
    print("=" * 60)
    print(f"  API : {FOG_API_URL}")
    print(f"  User: {FOG_USERNAME}")
    print(f"  Runs: {ITERATIONS}")
    print("=" * 60)

    # 1 – Load the Fog node's public key
    if not FOG_PUBLIC_KEY_PATH.exists():
        print(f"\n❌ Fog public key not found at {FOG_PUBLIC_KEY_PATH}")
        print("   Run `python scripts/generate_keys.py` first.")
        sys.exit(1)

    fog_public_key = HybridEncryptionService.load_public_key(FOG_PUBLIC_KEY_PATH)
    print(f"\n✔ Loaded Fog public key from {FOG_PUBLIC_KEY_PATH}")

    # 2 – Authenticate (session-based)
    session = requests.Session()
    print(f"\n🔐 Logging in as '{FOG_USERNAME}'…")

    # First GET the login page or CSRF cookie
    # For DRF SessionAuthentication we need CSRF token
    login_url = f"{FOG_API_URL}/auth/login/"

    # Get CSRF token
    csrf_resp = session.get(
        login_url,
        headers={"Accept": "application/json"},
    )
    csrf_token = session.cookies.get("csrftoken", "")

    login_resp = session.post(
        login_url,
        json={"username": FOG_USERNAME, "password": FOG_PASSWORD},
        headers={
            "Content-Type": "application/json",
            "X-CSRFToken": csrf_token,
        },
    )

    if login_resp.status_code != 200:
        print(f"❌ Login failed ({login_resp.status_code}): {login_resp.text}")
        sys.exit(1)

    print(f"✔ Login successful: {login_resp.json()}")

    # Update CSRF token after login (Django rotates it)
    csrf_token = session.cookies.get("csrftoken", csrf_token)

    # 3 – Simulate IoT data transmissions
    create_url = f"{FOG_API_URL}/records/create/"

    for i in range(1, ITERATIONS + 1):
        print(f"\n── Iteration {i}/{ITERATIONS} ──")

        # Generate sample data
        vital_signs = generate_vital_signs()
        patient_id = vital_signs["patient_id"]
        plaintext = json.dumps(vital_signs, separators=(",", ":"), sort_keys=True)

        print(f"   Patient: {patient_id}")
        print(f"   HR={vital_signs['vitals']['heart_rate']} bpm, "
              f"SpO2={vital_signs['vitals']['oxygen_saturation']}%, "
              f"Temp={vital_signs['vitals']['temperature_celsius']}°C")

        # Encrypt
        encrypted = HybridEncryptionService.encrypt(plaintext, fog_public_key)
        print(f"   🔒 Encrypted (hash={encrypted.integrity_hash[:16]}…)")

        # Build API payload
        api_payload = {
            "patient_id": patient_id,
            "encrypted_payload": encrypted.ciphertext_b64,
            "encrypted_aes_key": encrypted.encrypted_aes_key_b64,
            "ephemeral_public_key": encrypted.ephemeral_public_key_b64,
            "integrity_hash": encrypted.integrity_hash,
        }

        # Send to Fog API
        # Refresh CSRF token
        csrf_token = session.cookies.get("csrftoken", csrf_token)
        resp = session.post(
            create_url,
            json=api_payload,
            headers={
                "Content-Type": "application/json",
                "X-CSRFToken": csrf_token,
            },
        )

        if resp.status_code == 201:
            record_data = resp.json().get("data", {})
            print(f"   ✔ Record created: {record_data.get('id', 'N/A')}")
        else:
            print(f"   ❌ Failed ({resp.status_code}): {resp.text[:200]}")

    # 4 – Logout
    print("\n🔓 Logging out…")
    csrf_token = session.cookies.get("csrftoken", csrf_token)
    session.post(
        f"{FOG_API_URL}/auth/logout/",
        headers={"X-CSRFToken": csrf_token},
    )
    print("✔ Session closed.")
    print("\n✅ Simulation complete.")


if __name__ == "__main__":
    main()
