# Generated by Django 5.2.11 on 2026-02-23 13:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('READ', 'Read'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('FORWARD', 'Forward to Cloud')], db_index=True, help_text='The type of action performed.', max_length=10)),
                ('record_id', models.UUIDField(blank=True, db_index=True, help_text='UUID of the medical record involved.', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the client.', null=True)),
                ('details', models.TextField(blank=True, default='', help_text='Additional context about the action.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit logs',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
